### ISSUE TITLE
 python build_extend_utils_cffi.py Error

### ISSUE THREAD

**Issue by flowtcw** [zju-3dv/pvnet#10]
my gcc version is 5.4.0
and I revise the cuda_include and dart in build_extend_utils_cffi.py to be compatible with my CUDA in my computer.

and the error is:
leviathan@leviathan-1080ti:~/PycharmProjects/pvnet/lib/utils/extend_utils$ python build_extend_utils_cffi.py
In file included from ./include/ceres/internal/autodiff.h:147:0,
                 from ./include/ceres/autodiff_cost_function.h:133,
                 from ./include/ceres/ceres.h:37,
                 from src/uncertainty_pnp.cpp:3:
./include/ceres/internal/fixed_array.h:38:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/home/leviathan/PycharmProjects/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /home/leviathan/anaconda3/envs/torch0.4/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/leviathan/anaconda3/envs/torch0.4/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /home/leviathan/anaconda3/envs/torch0.4/compiler_compat -L/home/leviathan/anaconda3/envs/torch0.4/lib -Wl,-rpath=/home/leviathan/anaconda3/envs/torch0.4/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-9.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
gcc: error: src/uncertainty_pnp.cpp.o: No such file or directory
Traceback (most recent call last):
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/site-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/leviathan/anaconda3/envs/torch0.4/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by pengsida** [comment]
`./include/ceres/internal/fixed_array.h:38:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.`

It seems like a problem related to glog.
Do you have glog installed on your computer.

**Comment by pengsida** [comment]
Try `sudo apt-get install libgoogle-glog-dev`.
If it works, please tell me. Thank you.

**Comment by flowtcw** [comment]
> u.

It seems work, thank you!
And I have an another question is that export LD_LIDBRARY_PATH=$LD_LIDBRARY_PATH:/path/to/bb8-voter/lib/utils/extend_utils/lib
please tell me where is the path about bb8-voter.thank you =.=!

**Comment by pengsida** [comment]
bb8-voter -> pvnet

**Comment by joefriel** [comment]
Also, there is a misspelling.  LD_LIDBRARY_PATH should be LD_LIBRARY_PATH

**Comment by flowtcw** [comment]
> LD_LIDBRARY_PATH should be LD_LIBRARY_PATH

Do you mean that:export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/bb8-voter/lib/utils/extend_utils/lib?
thanks!

**Comment by joefriel** [comment]
Yes. LD_LIBRARY_PATH is the name of the environment variable that the system uses to determine where to look for libraries.  

This line appends the path of pvnet libraries (path/to/pvnet/lib/utils/extend_utils/lib) to the existing path.

"path/to/pvnet" is wherever you have installed pvnet

**Comment by flowtcw** [comment]
thanks a lot!
I have revise the command that ~/PycharmProjects/pvnet/lib/utils/extend_utils$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/leviathan/PycharmProjects/pvnet/lib/utils/extend_utils/lib

but when I run the next command python lib/utils/data_utils.py, I have a new error is that 
(torch0.4) leviathan@leviathan-1080ti:~/PycharmProjects/pvnet$ python lib/utils/data_utils.py
Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/leviathan/PycharmProjects/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

I  search for the file in the pvnet, but I can't find it.
thank you!

**Comment by joefriel** [comment]
libspqr is the library for libsuitesparse.  libsuitesparse is one of a number of requirements for ceres.

See http://ceres-solver.org/installation.html

You could try installing just libsuitesparse (sudo apt-get install libsuitesparse-dev)

I am not sure what you have loaded in your environment, there may also be other missing libraries.

**Comment by pengsida** [comment]
Thank you for your proofreading.

**Comment by flowtcw** [comment]
well, I successfully run the command python lib/utils/data_utils.py
I think you should update some command.
1:export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib
2:sudo apt-get install libgoogle-glog-dev
3:sudo apt-get install libsuitesparse-dev
4:sudo apt-get install libatlas-base-dev
5:the version of pytorch should be 0.4.1, otherwise the code of 'from torch.utils.data import Sampler' will can't find it.

Finally, thank to pengsida and joefriel!

**Comment by pengsida** [comment]
Thank you very much. I have updated the README.

**Comment by flowtcw** [comment]
Well, there is a new bug.I successfully run the command python lib/utils/data_utils.py, but when I run the demo, python tools/demo.py(I have download the pretrained model and put it in the $ROOT/data/model/cat_demo/199.pth. I renamed the file cat_199.pth to 199.pth)
the error is:
(torch0.4) leviathan@leviathan-1080ti:~/PycharmProjects/pvnet$ python tools/demo.py

Traceback (most recent call last):
  File "tools/demo.py", line 8, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/home/leviathan/PycharmProjects/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /home/leviathan/PycharmProjects/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by pengsida** [comment]
Use pytorch v0.4.1 to compile the Ransac Voting Layer again. This may help.

**Comment by flowtcw** [comment]
> Use pytorch v0.4.1 to compile the Ransac Voting Layer again. This may help.

I use pytorch v0.4.1 to compile the Ransac Voting Layer again and it dosen't work.

**Comment by pengsida** [comment]
How about adding `import torch` before `import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting`.
It is kind of weird, because it works fine to me.
Which version of python do you use, 2 or 3

**Comment by flowtcw** [comment]
My python version is 3.6. I delete the pvnet file and git clone again. It seems work. I can run python tools/demo.py
but the result is very strange. 
![Figure_1](https://user-images.githubusercontent.com/28707142/54927015-5d200880-4f4c-11e9-8a85-f5cc9cae9227.png)
![Figure_2](https://user-images.githubusercontent.com/28707142/54927065-71fc9c00-4f4c-11e9-86df-38200c6dba54.png)
I find that everytime I run the command, the result is different,OvO

**Comment by pengsida** [comment]
It is obvious that you do not load the pretrained model correctly.

**Comment by flowtcw** [comment]
> It is obvious that you do not load the pretrained model correctly.

I'm sorry. It's my fault. 
thanks a lot!
