### ISSUE TITLE
Question about the output in the paper

### ISSUE THREAD

**Issue by youkenhou** [zju-3dv/pvnet#3]
Thank you for your great work. However there are some questions confusing me in the paper.

According to the paper, the size of output tensor of unit vectors is `HxWx(Kx2xC)`. Does it mean that for each class of objects, every pixel has K unit vectors? Every pixel votes for all classes?

Another question is about the usage of FPS algorithm. Is it used to generate ground truth key points? Or the network outputs one key point and the others are generated by FPS?

Maybe these are some stupid questions but I would appreciate it if you explain them. Thanks in advance.

**Comment by pengsida** [comment]
1. C in our code is 1, which means that we actually handle a class of object in a single model.
2. The FPS algorithm runs at the very beginning to generate the ground truth keypoints.

**Comment by youkenhou** [comment]
I see. Thanks a lot.
