### ISSUE TITLE
how to get dense_pts.txt

### ISSUE THREAD

**Issue by DC1991** [zju-3dv/pvnet#5]
Dear author,

When I run 'lib/utils/data_utils.py', it shows: OSError: /home/xxx/pvnet/data/LINEMOD/ape/dense_pts.txt not found.

How can I generate dense_pts.txt.

**Comment by pengsida** [comment]
I have updated the LINEMOD dataset.
Please see the README.
There might be some other bugs, and please report them if you have any problems.
