### ISSUE TITLE
error in building build_extend_utils_cffi.py

### ISSUE THREAD

**Issue by kk1153** [zju-3dv/pvnet#6]
x86_64-linux-gnu-gcc: error: src/uncertainty_pnp.cpp.o: No such file or directory
x86_64-linux-gnu-gcc: error: ./lib/libceres.so: No such file or directory
x86_64-linux-gnu-gcc: error: ./lib/libglog.so: No such file or directory

**Comment by pengsida** [comment]
I upload the libceres.so and libglog.so 3 days ago.
Maybe you need update your code by `git pull`.

**Comment by kk1153** [comment]
src/uncertainty_pnp.cpp.o: No such file or directory 
still missing this

**Comment by pengsida** [comment]
`src/uncertainty_pnp.cpp.o` is an intermediate object file to generate the final so file.
We automatically delete it after the compiling procedure.
Please run `python build_extend_utils_cffi.py` under the directory `path/to/pvnet/lib/utils/extend_utils`.
We have tested in a new environment, and everything works fine.
If you still have question, please paste the error messages.

**Comment by kk1153** [comment]
Have a look
[error.txt](https://github.com/zju-3dv/pvnet/files/2969413/error.txt)

**Comment by pengsida** [comment]
Your gcc version does not fit with our code.
Please refer to https://stackoverflow.com/questions/33481831/default-random-engine-is-not-a-member-of-std 

My gcc version is 5.4.0.

**Comment by pengsida** [comment]
I have updated the README https://github.com/zju-3dv/pvnet#installation
