### ISSUE TITLE
Question about training times and parameters

### ISSUE THREAD

**Issue by joefriel** [zju-3dv/pvnet#9]
Thanks for making the code available.  I have successfully run the code on Google Colab (K80 GPU with 11G) and have reproduced the demo and testing results.  I have also trained ("cat") using 10000 synthetic images and 10000 Fuse images (no occlusion images) and a single epoch took 4 hours to complete.  I see that the pre-trained models use 200 epochs, which would imply 800 hours of training time (on a K80) per object. I am not sure if that time is expected or if I have an unknown issue.  Could you share the training parameters used to generate the 199.pth files and also any information on the training time?  Thanks again.

**Comment by pengsida** [comment]
We used 4 TITAN Xp to train, which took 20 hours per object.
I do not revise any training parameters.
Maybe it is a problem of the Cloud GPU. I am not sure.
